# -*- coding: utf-8 -*-
"""python-stdlib: the organism skeleton — printed from the reference (D27, rung 0).

The Python printer is FREE (D23): Expr and bodies are a Python subset, so
emit = ast.unparse with no transformations; state is dataclasses, whose
attributes match the genome fields byte-for-byte. Division/int semantics are
native = the canon. Parity with the core and go-stdlib: the same HTTP endpoints,
the events.jsonl format, windowed dedup, D25. Zero dependencies outside stdlib (D19).
"""
from __future__ import annotations

import ast
import pathlib
import textwrap

from onto.core import expr as E
from onto.core.genome import Genome


def _py(src_tree) -> str:
    return ast.unparse(src_tree)


def generate(g: Genome, outdir: str | pathlib.Path,
             skills_cache: str | pathlib.Path | None = None) -> pathlib.Path:
    out = pathlib.Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "organism.py").write_text(_organism_py(g, skills_cache),
                                     encoding="utf-8")
    return out


def _organism_py(g: Genome, skills_cache=None) -> str:
    P: list[str] = []
    add = P.append
    add(f'''"""Code generated by onto (python-stdlib dialect) from genome
'{g.name}'. DO NOT EDIT."""
import copy
import json
import os
import sys
import time
from collections import deque
from dataclasses import asdict, dataclass
from http.server import BaseHTTPRequestHandler, HTTPServer

RETRY_WINDOW = {g.retry_window}
''')
    add(_skills_block(g, skills_cache))
    # ---- states and events
    for en in sorted(g.entities):
        ent = g.entities[en]
        fields = "\n".join(
            f"    {f}: {'str' if ent.state[f] == 'str' else 'int'}"
            for f in sorted(ent.state))
        add(f"@dataclass\nclass {_cls(en)}State:\n{fields}\n")
    for evn in sorted(g.events):
        fields = "\n".join(
            f"    {f}: {'str' if t == 'str' else 'int'}"
            for f, t in sorted(g.events[evn].items()))
        add(f"@dataclass\nclass Ev{evn}:\n{fields}\n")
        conv = ", ".join(
            f"{f}=str(m['{f}'])" if t == "str" else f"{f}=int(m['{f}'])"
            for f, t in sorted(g.events[evn].items()))
        req = ", ".join(f"'{f}'" for f in sorted(g.events[evn]))
        add(f"""def decode_ev_{evn}(m):
    missing = [f for f in ({req},) if f not in m]
    if missing:
        raise ValueError(f"missing event fields: {{missing}}")
    return Ev{evn}({conv})
""")
    # ---- rules: printing bodies from the reference (emit = unparse, free)
    for en in sorted(g.entities):
        ent = g.entities[en]
        for rn in sorted(ent.rules):
            r = ent.rules[rn]
            fn = f"{en}_{rn}"
            if r.guard:
                add(f"def guard_{fn}(s, ev):\n    return "
                    + _py(E.parse_expr(r.guard)) + "\n")
            body = textwrap.indent(_py(E.parse_body(r.body)), "    ")
            add(f"def rule_{fn}(s, ev):\n    s = copy.copy(s)\n{body}\n    return s\n")
            if r.contract.post:
                add(f"def post_{fn}(s):\n    return "
                    + _py(E.parse_expr(r.contract.post)) + "\n")
            if r.contract.conserves:
                add(f"def conserves_{fn}(s):\n    return "
                    + _py(E.parse_expr(r.contract.conserves)) + "\n")

    # ---- organism
    add("""class Organism:
    def __init__(self, data_dir):
        self.data = data_dir
        self.seen = set()
        self.seen_q = deque()
        self.replaying = False
        self.counters = {"applied": 0, "dup": 0, "noop": 0, "rejected": 0,
                         "unknown_instance": 0, "invariant_violations": 0}
""")
    for en in sorted(g.entities):
        ent = g.entities[en]
        add(f"        self.{en} = {{}}")
        if ent.instances != "dynamic":                     # D51
            for inst in ent.instances:
                lits = ", ".join(f"{f}={ent.init[f]!r}" for f in sorted(ent.state))
                add(f"        self.{en}['{inst}'] = {_cls(en)}State({lits})")
    add("""
    def _ledger(self, kind, payload):
        if self.replaying or not self.data:
            return
        payload = {"kind": kind, **payload}
        with open(os.path.join(self.data, "ledger.jsonl"), "a", encoding="utf-8") as f:
            f.write(json.dumps(payload, ensure_ascii=False) + "\\n")

    def _append_log(self, event):
        if self.replaying or not self.data:
            return
        with open(os.path.join(self.data, "events.jsonl"), "a", encoding="utf-8") as f:
            f.write(json.dumps(event, ensure_ascii=False) + "\\n")
            f.flush()
            os.fsync(f.fileno())

    def _dedup(self, ev_id):
        if ev_id in self.seen:
            return True
        self.seen.add(ev_id)
        self.seen_q.append(ev_id)
        while len(self.seen_q) > RETRY_WINDOW:
            self.seen.discard(self.seen_q.popleft())
        return False
""")
    # lists for aggregates (the genome's instance order)
    for en in sorted(g.entities):
        if g.entities[en].instances == "dynamic":
            add(f"    def {en}_list(self):\n        return list(self.{en}.values())\n")
        else:
            insts = ", ".join(f"self.{en}['{i}']" for i in g.entities[en].instances)
            add(f"    def {en}_list(self):\n        return [{insts}]\n")
    # invariants/queries — printed from the reference; entity names are bound
    # to their lists by local variables
    ent_binds = "\n".join(f"        {en} = self.{en}_list()" for en in sorted(g.entities))
    for name in sorted(g.invariants):
        add(f"    def invariant_{name}(self):\n{ent_binds}\n        return "
            + _py(E.parse_expr(g.invariants[name])) + "\n")
    for name in sorted(g.queries):
        add(f"    def query_{name}(self):\n{ent_binds}\n        return "
            + _py(E.parse_expr(g.queries[name])) + "\n")
    qmap = ", ".join(f"'{n}': self.query_{n}" for n in sorted(g.queries))
    add(f"    def query(self, name):\n        q = {{{qmap}}}\n"
        "        return q[name]() if name in q else None\n")

    # fire by event type (entity order = the genome's)
    dispatch_arms = "\n".join(
        f"        elif typ == '{evn}':\n"
        f"            self.fire_{evn}(m, ev_id, outcomes, depth)"
        for evn in sorted(g.events))
    add(f"""    def dispatch(self, typ, m, ev_id, outcomes, depth):
        if depth > 8:
            self._ledger('cascade_overflow', {{'event': ev_id, 'type': typ}})
            outcomes['cascade:' + typ] = 'overflow'
            return
        if False:
            pass
{dispatch_arms}
""")
    for evn in sorted(g.events):
        lines = [f"    def fire_{evn}(self, m, ev_id, outcomes, depth=0):",
                 f"        ev = decode_ev_{evn}(m)"]
        any_rule = False
        for en, ent in g.entities.items():
            for rn, r in ent.rules.items():
                if r.when != evn:
                    continue
                any_rule = True
                fn = f"{en}_{rn}"
                key = g.key_field(en)
                if ent.instances == "dynamic":
                    lits = ", ".join(
                        f"{f}={ent.init.get(f, '' if ent.state[f] == 'str' else 0)!r}"
                        for f in sorted(ent.state))
                    L = [f"inst = m.get('{key}')",
                         f"st = self.{en}.get(inst)",
                         "if st is None and isinstance(inst, str) and inst:",
                         f"    st = {_cls(en)}State({lits})",
                         f"    self.{en}[inst] = st",
                         "if st is None:",
                         "    self.counters['unknown_instance'] += 1",
                         f"    outcomes['{en}.{rn}'] = 'unknown-instance:' + str(inst)"]
                else:
                    L = [f"inst = m.get('{key}')",
                         f"st = self.{en}.get(inst)",
                         "if st is None:",
                         "    self.counters['unknown_instance'] += 1",
                         f"    outcomes['{en}.{rn}'] = 'unknown-instance:' + str(inst)"]
                if r.guard:
                    L += [f"elif not guard_{fn}(st, ev):",
                          "    self.counters['noop'] += 1",
                          f"    outcomes['{en}.{rn}'] = 'noop(guard)'"]
                L += ["else:",
                      f"    nxt = rule_{fn}(st, ev)"]
                branch = "if"
                if r.contract.post:
                    L += [f"    {branch} not post_{fn}(nxt):",
                          "        self.counters['rejected'] += 1",
                          f"        self._ledger('contract_post', {{'entity': '{en}', 'rule': '{rn}', 'instance': inst, 'event': ev_id}})",
                          f"        outcomes['{en}.{rn}'] = 'rejected(post)'"]
                    branch = "elif"
                if r.contract.conserves:
                    L += [f"    {branch} conserves_{fn}(st) != conserves_{fn}(nxt):",
                          "        self.counters['rejected'] += 1",
                          f"        self._ledger('contract_conserves', {{'entity': '{en}', 'rule': '{rn}', 'instance': inst, 'event': ev_id}})",
                          f"        outcomes['{en}.{rn}'] = 'rejected(conserves)'"]
                    branch = "elif"
                emit_lines = []
                for k_e, em in enumerate(r.emit):
                    import ast as _ast
                    cond = _ast.unparse(E.parse_expr(em.when)) if em.when else "True"
                    fld = ", ".join(
                        f"'{f}': ({_ast.unparse(E.parse_expr(src))})"
                        for f, src in em.fields.items())
                    emit_lines += [
                        "    s = nxt   # policies (D54): fields from the POST-state",
                        f"    if {cond}:",
                        f"        self.dispatch('{em.event}', {{{fld}}}, "
                        f"ev_id + ':p{k_e}', outcomes, depth + 1)"]
                if branch == "if":
                    L += [f"    self.{en}[inst] = nxt",
                          f"    outcomes['{en}.{rn}'] = 'applied'"] + emit_lines
                else:
                    L += ["    else:",
                          f"        self.{en}[inst] = nxt",
                          f"        outcomes['{en}.{rn}'] = 'applied'"] + \
                         ["    " + l for l in emit_lines]
                lines += ["        " + x for x in L]
        if not any_rule:
            lines.append("        pass")
        add("\n".join(lines) + "\n")

    inv_checks = "\n".join(
        f"        if not self.invariant_{n}():\n"
        f"            self.counters['invariant_violations'] += 1\n"
        f"            self._ledger('invariant_violation', {{'invariant': '{n}', 'event': ev_id}})"
        for n in sorted(g.invariants)) or "        pass"

    add(f"""    def handle(self, m):
        ev_id = m.get("id")
        if not isinstance(ev_id, str) or not ev_id:
            return {{"status": "error", "reason": "event requires non-empty str 'id'"}}
        typ = m.get("type")
        if typ not in {sorted(g.events)!r}:
            return {{"status": "error", "reason": f"unknown event type '{{typ}}'"}}
        self._append_log(m)
        if self._dedup(ev_id):
            self.counters["dup"] += 1
            return {{"status": "dup", "id": ev_id}}
        outcomes = {{}}
        outcomes_err = None
        self.dispatch(typ, m, ev_id, outcomes, 0)
{inv_checks}
        self.counters["applied"] += 1
        return {{"status": "applied", "id": ev_id, "outcomes": outcomes}}

    def replay(self):
        path = os.path.join(self.data, "events.jsonl")
        if not self.data or not os.path.exists(path):
            return 0
        self.replaying = True
        n = 0
        for line in open(path, encoding="utf-8"):
            if line.strip():
                self.handle(json.loads(line))
                n += 1
        self.replaying = False
        self._ledger("replay", {{"events": n}})
        return n

    def state_of(self, entity, inst):
        ent = getattr(self, entity, None)
        if isinstance(ent, dict) and inst in ent:
            return asdict(ent[inst])
        return None
""".replace("{{", "{").replace("}}", "}"))

    # ---- HTTP + bench
    add(_serve_py(g))
    return "\n".join(P)


def _cls(en: str) -> str:
    return "".join(w.capitalize() for w in en.split("_"))


def _serve_py(g: Genome) -> str:
    # bench rule-path: the first rule with a guard and post (parity with go/rulebench)
    rb = ""
    for en, ent in g.entities.items():
        for rn, r in ent.rules.items():
            if r.guard and r.contract.post:
                fn = f"{en}_{rn}"
                init = ", ".join(f"{f}={ent.init[f]}" for f in sorted(ent.state))
                ev_lits = ", ".join(
                    f"{f}=" + ("'x'" if t == "str" else "1")
                    for f, t in sorted(g.events[r.when].items()))
                rb = f"""    s0 = {_cls(en)}State({init})
    ev0 = Ev{r.when}({ev_lits})
    M = 1000000
    t1 = time.perf_counter()
    acc = 0
    for _ in range(M):
        if guard_{fn}(s0, ev0):
            nxt = rule_{fn}(s0, ev0)
            if post_{fn}(nxt):
                acc += 1
    el2 = time.perf_counter() - t1
    print(f"bench rule-path ({en}.{rn}): {{el2 / M * 1e9:.1f}} ns/op (acc={{acc}})")"""
                break
        if rb:
            break
    if not g.events:      # a pure kernel (skills only): nothing to bench
        return "def run_bench():\n    print('bench: no events (pure kernel)')\n"
    return f"""def run_bench():
    org = Organism("")
    N = 20000
    raws = [json.dumps({{"id": f"b{{i}}", "type": {next(iter(sorted(g.events)))!r},
                        **{{k: ("x" if t == "str" else 1)
                           for k, t in {dict(sorted(g.events[next(iter(sorted(g.events)))].items()))!r}.items()}}}})
            for i in range(N)]
    t0 = time.perf_counter()
    for r in raws:
        org.handle(json.loads(r))
    el = time.perf_counter() - t0
    print(f"bench full-path: {{N}} events, {{el / N * 1e9:.0f}} ns/op, {{N / el:.0f}} events/s")
{rb}


def main():
    port, data, bench = 8090, "./data", False
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] == "--port":
            i += 1; port = int(args[i])
        elif args[i] == "--data":
            i += 1; data = args[i]
        elif args[i] == "bench":
            bench = True
        i += 1
    if bench:
        run_bench()
        return
    os.makedirs(data, exist_ok=True)
    org = Organism(data)
    org.replay()

    class H(BaseHTTPRequestHandler):
        def log_message(self, *a):
            pass

        def _send(self, code, obj):
            body = json.dumps(obj, ensure_ascii=False).encode()
            self.send_response(code)
            self.send_header("Content-Type", "application/json; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def do_POST(self):
            if self.path.startswith("/skill/"):
                name = self.path.split("/", 2)[2]
                if name not in SKILLS:
                    return self._send(404, {{"error": f"skill '{{name}}' not printed"}})
                n = int(self.headers.get("Content-Length", 0))
                try:
                    case = json.loads(self.rfile.read(n) or b"{{}}")
                except Exception as e:
                    return self._send(400, {{"error": f"bad json: {{e}}"}})
                try:
                    out = _run_skill(name, case)
                except Exception as e:
                    return self._send(422, {{"error": f"{{type(e).__name__}}: {{e}}"}})
                return self._send(200, out)
            if self.path != "/event":
                return self._send(404, {{"error": "unknown path"}})
            n = int(self.headers.get("Content-Length", 0))
            try:
                m = json.loads(self.rfile.read(n) or b"{{}}")
            except Exception as e:
                return self._send(400, {{"error": f"bad json: {{e}}"}})
            out = org.handle(m)
            self._send(200 if out.get("status") != "error" else 422, out)

        def do_GET(self):
            from urllib.parse import unquote
            parts = [unquote(p) for p in self.path.split("/") if p]
            if parts == ["health"]:
                return self._send(200, {{"ok": True, "counters": org.counters,
                                        "genome": {g.name!r}}})
            if len(parts) == 3 and parts[0] == "state":
                st = org.state_of(parts[1], parts[2])
                if st is None:
                    return self._send(404, {{"error": "no state"}})
                return self._send(200, st)
            if len(parts) == 2 and parts[0] == "q":
                v = org.query(parts[1])
                if v is None:
                    return self._send(404, {{"error": "unknown query"}})
                return self._send(200, {{"value": v}})
            self._send(404, {{"error": "unknown path"}})

    print(f"organism {g.name!r} (python-stdlib, printed from reference) on :{{port}}")
    HTTPServer(("127.0.0.1", port), H).serve_forever()


if __name__ == "__main__":
    main()
"""


def _skills_block(g: Genome, skills_cache) -> str:
    """U7 (D71): printing CERTIFIED skill bodies from the ribosome cache into
    the phenotype (fast takes priority, naive is the fallback). A skill with no
    body in the cache is not printed — an honest 404 (synthesize first). The
    ribosome's gates have already passed — printing does not re-judge; parity
    with the canon is judged by the exam."""
    import pathlib as _pl
    from onto.core import skills as SK
    P = ["from types import SimpleNamespace\n", "SKILLS = {}\n"]
    if skills_cache and g.skills:
        cache = _pl.Path(skills_cache)
        for name, raw_sk in g.skills.items():
            sk = SK.Skill.model_validate(raw_sk)
            for phase in ("fast", "naive"):
                f = cache / f"{name}.{phase}.py"
                if not f.exists():
                    continue
                for tname, tfields in sk.types.items():
                    P.append(f"def {tname}(*a, **kw):\n"
                             f"    d = dict(zip({list(tfields)!r}, a)); d.update(kw)\n"
                             f"    return SimpleNamespace(**d)\n")
                P.append(f"# --- skill '{name}' ({phase}, certified by ribosome gates)")
                P.append(f.read_text(encoding="utf-8").rstrip() + "\n")
                ret_fields = list(SK._elem_type(sk.returns, sk.types))
                P.append(f"SKILLS[{name!r}] = ({phase}_{name}, "
                         f"{list(sk.params)!r}, {ret_fields!r}, {phase!r})\n")
                break
    P.append(
        "def _run_skill(name, case):\n"
        "    fn, params, ret_fields, phase = SKILLS[name]\n"
        "    args = [[SimpleNamespace(**it) for it in case[p]] for p in params]\n"
        "    out = fn(*args)\n"
        "    norm = [{f: (o if isinstance(o, dict) else vars(o))[f] "
        "for f in ret_fields} for o in out]\n"
        "    return {'out': norm, 'body': phase}\n")
    return "\n".join(P)
