# -*- coding: utf-8 -*-
"""rust-stdlib skeleton: a genome -> a std-only Rust organism.

D97 (channel axis): the BRAIN (structs/decode/guard/rule/dispatch/fold) is
printed from the genome; the DOOR is a transport functor SELECTED FROM SPEC
(ports.yaml driver), not hardcoded. std-only drivers: file / stdio / tcp / http
(Rust std has no http lib, so http/tcp are a raw TcpListener). Same fold, any
channel — certified by fold-parity across channels (exam fchannels). Fixed +
dynamic instances, guard/body/post/conserves and the D54 emit-cascade supported.
Codec is currently json/flat (codec-as-axis = a later phase, grown via growport).
"""
from __future__ import annotations

import ast
import pathlib

from onto.core import expr as E
from onto.core.genome import Genome
from .emit import RUST_HELPERS, emit_body, emit_expr


def _rtype(t: str) -> str:
    return "String" if t == "str" else "i64"


def _lit(ent, f) -> str:
    t = ent.state[f]
    v = ent.init.get(f, "" if t == "str" else 0)
    return f'"{v}".to_string()' if t == "str" else f"{v}i64"


def _default_channels() -> list[dict]:
    # the door is a functor SELECTED FROM SPEC (D97); default = a file in-driver.
    return [{"driver": "file", "direction": "in", "codec": "json"}]


def generate(g: Genome, outdir: str | pathlib.Path, skills_cache=None,
             channels: list[dict] | None = None) -> pathlib.Path:
    out = pathlib.Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "main.rs").write_text(
        _organism_rs(g, channels or _default_channels()), encoding="utf-8")
    return out


def _organism_rs(g: Genome, channels: list[dict]) -> str:
    P: list[str] = []
    add = P.append
    add(f"// Code generated by onto (rust-stdlib dialect) from genome "
        f"'{g.name}'. DO NOT EDIT.")
    add("#![allow(unused, non_snake_case, non_camel_case_types)]")
    add("use std::collections::HashMap;\nuse std::collections::VecDeque;")
    add("use std::io::{Read, Write, BufRead, BufReader};")
    add(RUST_HELPERS)
    add(f"const RETRY_WINDOW: usize = {g.retry_window};\n")

    # ---- a minimal flat-JSON value + line parser (events are flat str/int) ----
    add(r'''#[derive(Clone, Debug)]
enum Val { I(i64), S(String), B(bool) }
impl Val {
    fn as_i(&self) -> i64 { if let Val::I(v) = self { *v } else if let Val::B(b)=self { *b as i64 } else { 0 } }
    fn as_s(&self) -> String { if let Val::S(v) = self { v.clone() } else { String::new() } }
}
fn parse_flat(line: &str) -> HashMap<String, Val> {
    // lenient parser for a FLAT json object {"k": v, ...} (no nested/comma-in-string)
    let mut m = HashMap::new();
    let t = line.trim();
    let t = t.trim_start_matches('{').trim_end_matches('}');
    for part in split_top(t) {
        let part = part.trim();
        if part.is_empty() { continue; }
        let idx = match part.find(':') { Some(i) => i, None => continue };
        let key = part[..idx].trim().trim_matches('"').to_string();
        let raw = part[idx+1..].trim();
        let v = if raw.starts_with('"') {
            Val::S(raw.trim_matches('"').replace("\\\"", "\"").to_string())
        } else if raw == "true" { Val::B(true) }
          else if raw == "false" { Val::B(false) }
          else { Val::I(raw.parse::<i64>().unwrap_or(0)) };
        m.insert(key, v);
    }
    m
}
fn split_top(s: &str) -> Vec<String> {
    let mut out = Vec::new(); let mut cur = String::new(); let mut inq = false;
    let mut prev = ' ';
    for c in s.chars() {
        if c == '"' && prev != '\\' { inq = !inq; }
        if c == ',' && !inq { out.push(cur.clone()); cur.clear(); prev = c; continue; }
        cur.push(c); prev = c;
    }
    if !cur.trim().is_empty() { out.push(cur); }
    out
}
fn parse_kv(line: &str) -> HashMap<String, Val> {
    let mut m = HashMap::new();
    for part in line.trim().split(';') {
        let p = part.trim();
        if p.is_empty() { continue; }
        if let Some(i) = p.find('=') {
            let k = p[..i].trim().to_string();
            let v = p[i+1..].trim().to_string();
            let val = if let Ok(n) = v.parse::<i64>() { Val::I(n) } else { Val::S(v) };
            m.insert(k, val);
        }
    }
    m
}
fn child_json(m: &HashMap<String,Val>) -> String {
    let mut keys: Vec<&String> = m.keys().collect(); keys.sort();
    let parts: Vec<String> = keys.iter().map(|k| match &m[*k] {
        Val::I(v) => format!("\"{}\":{}", k, v),
        Val::S(v) => format!("\"{}\":\"{}\"", k, v),
        Val::B(v) => format!("\"{}\":{}", k, v),
    }).collect();
    format!("{{{}}}", parts.join(","))
}
''')

    # ---- entity state structs ----
    for en in sorted(g.entities):
        ent = g.entities[en]
        fields = "\n".join(f"    {f}: {_rtype(ent.state[f])}," for f in sorted(ent.state))
        add(f"#[derive(Clone)]\nstruct {en.capitalize()}State {{\n{fields}\n}}")
        lits = ", ".join(f"{f}: {_lit(ent, f)}" for f in sorted(ent.state))
        add(f"impl {en.capitalize()}State {{ fn init() -> Self {{ Self {{ {lits} }} }} }}\n")

    # ---- typed event structs + decode (like Go's decodeEv<Name>) ----
    for evn in sorted(g.events):
        flds = g.events[evn]
        sfields = "\n".join(f"    {f}: {_rtype(t)}," for f, t in sorted(flds.items()))
        add(f"#[derive(Clone)]\nstruct Ev{evn} {{\n{sfields}\n}}")
        pulls = []
        for f, t in sorted(flds.items()):
            getter = ".as_s()" if t == "str" else ".as_i()"
            default = 'String::new()' if t == "str" else "0i64"
            pulls.append(f'        {f}: m.get("{f}").map(|v| v{getter}).unwrap_or({default}),')
        add(f"fn decode_{evn}(m: &HashMap<String,Val>) -> Ev{evn} {{\n"
            f"    Ev{evn} {{\n" + "\n".join(pulls) + "\n    }\n}\n")

    # ---- rule fns: guard/body/post/conserves (typed ev) ----
    for en in sorted(g.entities):
        ent = g.entities[en]
        stt = f"{en.capitalize()}State"
        for rn in sorted(ent.rules):
            r = ent.rules[rn]
            names = {"s": "s", "ev": "ev"}
            fn = f"{en}_{rn}"
            evt = f"Ev{r.when}"
            if r.guard:
                add(f"fn guard_{fn}(s: &{stt}, ev: &{evt}) -> bool {{ "
                    + emit_expr(E.parse_expr(r.guard), names) + " }")
            body = emit_body(E.parse_body(r.body), names, indent="    ")
            add(f"fn rule_{fn}(s0: &{stt}, ev: &{evt}) -> {stt} {{\n"
                f"    let mut s = s0.clone();\n{body}\n    s\n}}")
            if r.contract.post:
                add(f"fn post_{fn}(s: &{stt}) -> bool {{ "
                    + emit_expr(E.parse_expr(r.contract.post), {"s": "s"}) + " }")
            if r.contract.conserves:
                add(f"fn cons_{fn}(s: &{stt}) -> i64 {{ "
                    + emit_expr(E.parse_expr(r.contract.conserves), {"s": "s"}) + " }")
    add("")

    # ---- organism ----
    st_fields = "\n".join(f"    {en}: HashMap<String, {en.capitalize()}State>,"
                          for en in sorted(g.entities))
    add(f"struct Organism {{\n{st_fields}\n    seen: HashMap<String,bool>,\n"
        f"    seen_q: VecDeque<String>,\n    counters: HashMap<String,i64>,\n"
        f"    out_events: Vec<String>,\n}}")

    inits = []
    for en in sorted(g.entities):
        ent = g.entities[en]
        inits.append(f"        let mut {en}: HashMap<String,{en.capitalize()}State> = HashMap::new();")
        if ent.instances != "dynamic":
            for inst in ent.instances:
                inits.append(f'        {en}.insert("{inst}".to_string(), {en.capitalize()}State::init());')
    field_set = ", ".join(sorted(g.entities))
    add("impl Organism {\n    fn new() -> Self {\n" + "\n".join(inits)
        + f"\n        Organism {{ {field_set}, seen: HashMap::new(), "
        f"seen_q: VecDeque::new(), counters: HashMap::new(), out_events: Vec::new() }}\n    }}")

    # entity lists for aggregates (invariants/queries)
    for en in sorted(g.entities):
        ent = g.entities[en]
        order = (f'let mut v: Vec<{en.capitalize()}State> = self.{en}.values().cloned().collect(); v'
                 if ent.instances == "dynamic"
                 else "vec![" + ", ".join(f'self.{en}["{i}"].clone()' for i in ent.instances) + "]")
        add(f"    fn {en}_list(&self) -> Vec<{en.capitalize()}State> {{ {order} }}")

    lists_names = {en: f"self.{en}_list()" for en in g.entities}
    for name in sorted(g.queries):
        tree = E.parse_expr(g.queries[name])
        ret = "i64" if E.typecheck_expr(tree, g.lists_env_types()) == "int" else "bool"
        add(f"    fn query_{name}(&self) -> {ret} {{ "
            + emit_expr(tree, lists_names) + " }")

    # dedup
    add("""    fn dedup(&mut self, id: &str) -> bool {
        if self.seen.contains_key(id) { return true; }
        self.seen.insert(id.to_string(), true);
        self.seen_q.push_back(id.to_string());
        while self.seen_q.len() > RETRY_WINDOW {
            if let Some(old) = self.seen_q.pop_front() { self.seen.remove(&old); }
        }
        false
    }""")

    # dispatch + fire per event
    fire_arms = []
    for evn in sorted(g.events):
        arms = []
        for en, ent in g.entities.items():
            for rn, r in ent.rules.items():
                if r.when != evn:
                    continue
                fn = f"{en}_{rn}"
                key = g.key_field(en)
                cap = en.capitalize()
                grd = (f"                if !guard_{fn}(st, &ev) {{ break 'arm; }}\n"
                       if r.guard else "")
                post_chk = ""
                if r.contract.post:
                    post_chk += (f"                if !post_{fn}(&next) {{ "
                                 f"*self.counters.entry(\"rejected\".into()).or_insert(0)+=1; break 'arm; }}\n")
                if r.contract.conserves:
                    post_chk += (f"                if cons_{fn}(st) != cons_{fn}(&next) {{ "
                                 f"*self.counters.entry(\"rejected\".into()).or_insert(0)+=1; break 'arm; }}\n")
                if ent.instances == "dynamic":
                    ensure = (f'                let inst = evm.get("{key}").map(|v| v.as_s()).unwrap_or_default();\n'
                              f"                if inst.is_empty() {{ break 'arm; }}\n"
                              f"                self.{en}.entry(inst.clone()).or_insert_with({cap}State::init);\n"
                              f"                let st = self.{en}.get(&inst).unwrap();\n")
                else:
                    ensure = (f'                let inst = evm.get("{key}").map(|v| v.as_s()).unwrap_or_default();\n'
                              f"                if !self.{en}.contains_key(&inst) {{ break 'arm; }}\n"
                              f"                let st = self.{en}.get(&inst).unwrap();\n")
                emits = ""
                for k_e, em in enumerate(r.emit):
                    names_e = {"s": "&next", "ev": "ev"}
                    flds = []
                    for f, src in em.fields.items():
                        printed = emit_expr(E.parse_expr(src), {"s": "next", "ev": "ev"})
                        ftype = g.events[em.event][f]
                        val = (f'Val::S({printed})' if ftype == "str" else f'Val::I({printed})')
                        # translate ev.<x>/next.<x> field access into map/struct reads
                        flds.append(f'                    child.insert("{f}".to_string(), {val});')
                    cond = (emit_expr(E.parse_expr(em.when), {"s": "next", "ev": "ev"})
                            if em.when else "true")
                    emits += (f'                if {cond} {{\n'
                              f'                    let mut child: HashMap<String,Val> = HashMap::new();\n'
                              f'                    child.insert("type".to_string(), Val::S("{em.event}".to_string()));\n'
                              + "\n".join(flds) + "\n"
                              f'                    self.out_events.push(child_json(&child));\n'
                              f'                    self.dispatch(&child, depth+1);\n'
                              f'                }}\n')
                arms.append(
                    f"            'arm: {{\n{ensure}{grd}"
                    f"                let next = rule_{fn}(st, &ev);\n{post_chk}"
                    f"                self.{en}.insert(inst.clone(), next.clone());\n"
                    f"                *self.counters.entry(\"applied\".into()).or_insert(0)+=1;\n"
                    f"{emits}            }}")
        arms_s = "\n".join(arms)
        fire_arms.append(f'        if typ == "{evn}" {{\n            let ev = decode_{evn}(&evm);\n{arms_s}\n        }}')
    fire_body = "\n".join(fire_arms)
    add(f"""    fn dispatch(&mut self, evm: &HashMap<String,Val>, depth: i64) {{
        if depth > 8 {{ return; }}
        let evm = evm.clone();
        let typ = evm.get("type").map(|v| v.as_s()).unwrap_or_default();
{fire_body}
    }}
    fn handle(&mut self, evm: HashMap<String,Val>) {{
        let id = evm.get("id").map(|v| v.as_s()).unwrap_or_default();
        if !id.is_empty() && self.dedup(&id) {{ return; }}
        self.dispatch(&evm, 0);
    }}""")

    # print final state as JSON
    # ---- dump the final fold as JSON: {"en":{"inst":{"field":v,...},...},...}
    dump_lines = ['    fn dump(&self) -> String {',
                  '        let mut out = String::from("{");']
    for i, en in enumerate(sorted(g.entities)):
        ent = g.entities[en]
        parts = []
        for f in sorted(ent.state):
            if ent.state[f] == "str":
                parts.append(f'format!("\\"{f}\\":\\"{{}}\\"", st.{f})')
            else:
                parts.append(f'format!("\\"{f}\\":{{}}", st.{f})')
        fields_expr = "[" + ", ".join(parts) + "].join(\",\")"
        if i > 0:
            dump_lines.append('        out.push_str(",");')
        dump_lines.append(f'        out.push_str("\\"{en}\\":{{");')
        dump_lines.append(f'        let mut keys: Vec<&String> = self.{en}.keys().collect(); keys.sort();')
        dump_lines.append('        for (j,k) in keys.iter().enumerate() {')
        dump_lines.append(f'            let st = &self.{en}[*k];')
        dump_lines.append('            if j>0 { out.push_str(","); }')
        dump_lines.append(f'            out.push_str(&format!("\\"{{}}\\":{{{{{{}}}}}}", k, {fields_expr}));')
        dump_lines.append('        }')
        dump_lines.append('        out.push_str("}");')
    dump_lines.append('        out.push_str("}");')
    dump_lines.append('        out')
    dump_lines.append('    }')
    # single-instance state as JSON (for GET /state/<en>/<inst>)
    dump_lines.append('    fn state_json(&self, en: &str, inst: &str) -> Option<String> {')
    for en in sorted(g.entities):
        ent = g.entities[en]
        parts = []
        for f in sorted(ent.state):
            if ent.state[f] == "str":
                parts.append(f'format!("\\"{f}\\":\\"{{}}\\"", st.{f})')
            else:
                parts.append(f'format!("\\"{f}\\":{{}}", st.{f})')
        fields_expr = "[" + ", ".join(parts) + "].join(\",\")"
        dump_lines.append(f'        if en == "{en}" {{ return self.{en}.get(inst)'
                          f'.map(|st| format!("{{{{{{}}}}}}", {fields_expr})); }}')
    dump_lines.append('        None')
    dump_lines.append('    }')
    dump_lines.append('}')
    add("\n".join(dump_lines))

    # ---- DOOR: a transport functor SELECTED FROM SPEC (D97). The brain above
    # is genome-printed; the door below is chosen by ports.yaml (driver). Same
    # fold, any channel: file / stdio / tcp / http. Certified by fold-parity.
    add(_emit_doors(channels))
    return "\n".join(P)


def _emit_doors(channels: list[dict]) -> str:
    ins = [c for c in channels if c.get("direction", "in") == "in"]
    ch = ins[0] if ins else {"driver": "file"}
    driver = ch.get("driver", "file")
    codec = ch.get("codec", "json")
    decoder = "parse_kv" if codec == "kv" else "parse_flat"
    P: list[str] = [f"fn parse_wire(line: &str) -> HashMap<String, Val> {{ {decoder}(line) }}"]
    # shared HTTP/TCP request plumbing, emitted only when needed
    if driver in ("http", "tcp"):
        P.append(r'''fn route(org: &mut Organism, method: &str, path: &str, body: &str) -> (u16, String) {
    if method == "POST" && path == "/event" { org.handle(parse_wire(body)); return (200, "{\"status\":\"applied\"}".to_string()); }
    if method == "GET" && path == "/health" { return (200, "{\"ok\":true}".to_string()); }
    if method == "GET" && path == "/dump" { return (200, org.dump()); }
    let segs: Vec<&str> = path.trim_matches('/').split('/').collect();
    if method == "GET" && segs.len() == 3 && segs[0] == "state" {
        return match org.state_json(segs[1], segs[2]) { Some(js) => (200, js), None => (404, "{\"error\":\"no such state\"}".to_string()) };
    }
    (404, "{\"error\":\"unknown route\"}".to_string())
}''')
    if driver == "http":
        P.append(r'''fn handle_http(stream: &mut std::net::TcpStream, org: &mut Organism) {
    let peer = match stream.try_clone() { Ok(s) => s, Err(_) => return };
    let mut reader = BufReader::new(peer);
    let mut line = String::new();
    if reader.read_line(&mut line).is_err() { return; }
    let parts: Vec<&str> = line.split_whitespace().collect();
    if parts.len() < 2 { return; }
    let (method, path) = (parts[0].to_string(), parts[1].to_string());
    let mut clen = 0usize;
    loop {
        let mut h = String::new();
        if reader.read_line(&mut h).is_err() { return; }
        if h == "\r\n" || h == "\n" || h.is_empty() { break; }
        if h.to_lowercase().starts_with("content-length:") { clen = h[15..].trim().parse().unwrap_or(0); }
    }
    let mut body = vec![0u8; clen];
    if clen > 0 && reader.read_exact(&mut body).is_err() { return; }
    let (code, resp) = route(org, &method, &path, &String::from_utf8_lossy(&body));
    let out = format!("HTTP/1.1 {} OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}", code, resp.len(), resp);
    let _ = stream.write_all(out.as_bytes());
}''')
    if driver == "tcp":
        P.append(r'''fn handle_tcp(stream: &mut std::net::TcpStream, org: &mut Organism) {
    let peer = match stream.try_clone() { Ok(s) => s, Err(_) => return };
    let mut reader = BufReader::new(peer);
    let mut line = String::new();
    while reader.read_line(&mut line).unwrap_or(0) > 0 {
        let t = line.trim().to_string();
        let resp = if t.is_empty() { String::new() }
            else if t == "?dump" { org.dump() }
            else if let Some(rest) = t.strip_prefix("?state/") {
                let s: Vec<&str> = rest.split('/').collect();
                if s.len() == 2 { org.state_json(s[0], s[1]).unwrap_or("null".to_string()) } else { "null".to_string() }
            } else { let (_c, r) = route(org, "POST", "/event", &t); r };
        if !resp.is_empty() { let _ = stream.write_all((resp + "\n").as_bytes()); }
        line.clear();
    }
}''')
    # main: the chosen driver, baked in from the spec (with runtime overrides)
    bind = ch.get("bind", "127.0.0.1:8610")
    path = ch.get("path", "")
    if driver == "file":
        # OUT/async direction (D97 Wave 5): drain the D54 emissions to a sink,
        # filtered by the out-channel's `on`. This is the async push half — the
        # emitted event leaves the organism to another channel.
        outs = [c for c in channels if c.get("direction") == "out"]
        drain = ""
        for oc in outs:
            if oc.get("driver", "file") != "file":
                continue
            sink = oc.get("path", "out.jsonl")
            on = oc.get("on", [])
            cond = (" || ".join(f'ev.contains("\\"type\\":\\"{e}\\"")' for e in on)
                    if on else "true")
            drain += ('    { use std::io::Write; let mut sink = std::fs::OpenOptions::new()'
                      f'.create(true).write(true).truncate(true).open("{sink}").unwrap();\n'
                      f'      for ev in &org.out_events {{ if {cond} {{ let _ = writeln!(sink, "{{}}", ev); }} }} }}\n')
        P.append(('fn main() {\n'
                  '    let args: Vec<String> = std::env::args().collect();\n'
                  '    let mut org = Organism::new();\n'
                  '    let src = if args.len() > 1 { args[1].clone() } else { "%PATH%".to_string() };\n'
                  '    if !src.is_empty() {\n'
                  '        let text = std::fs::read_to_string(&src).unwrap_or_default();\n'
                  '        for l in text.lines() { if !l.trim().is_empty() { org.handle(parse_wire(l)); } }\n'
                  '    }\n'
                  '%DRAIN%'
                  '    println!("{}", org.dump());\n'
                  '}').replace("%PATH%", path).replace("%DRAIN%", drain))
    elif driver == "stdio":
        P.append(r'''fn main() {
    let mut org = Organism::new();
    let stdin = std::io::stdin();
    for line in stdin.lock().lines() {
        if let Ok(l) = line { if !l.trim().is_empty() { org.handle(parse_wire(&l)); } }
    }
    println!("{}", org.dump());
}''')
    elif driver in ("http", "tcp"):
        handler = "handle_http" if driver == "http" else "handle_tcp"
        label = "HTTP" if driver == "http" else "TCP"
        P.append(r'''fn main() {
    let args: Vec<String> = std::env::args().collect();
    let mut bind = "%BIND%".to_string();
    let mut i = 1;
    while i < args.len() {
        if args[i] == "--port" && i + 1 < args.len() { bind = format!("127.0.0.1:{}", args[i+1]); }
        if args[i] == "--bind" && i + 1 < args.len() { bind = args[i+1].clone(); }
        i += 1;
    }
    let listener = std::net::TcpListener::bind(&bind).expect("bind failed");
    eprintln!("rust-stdlib organism (%LABEL% door) serving on {}", bind);
    let mut org = Organism::new();
    for stream in listener.incoming() {
        if let Ok(mut s) = stream { %HANDLER%(&mut s, &mut org); }
    }
}'''.replace("%BIND%", bind).replace("%LABEL%", label).replace("%HANDLER%", handler))
    else:
        P.append('fn main() { eprintln!("unknown driver"); }')
    return "\n\n".join(P)
