# -*- coding: utf-8 -*-
"""rust-stdlib skeleton: a genome -> a std-only Rust organism (BATCH mode).

Rust's std has no HTTP server (unlike Go's net/http), so the materialized Rust
organism is a BATCH runner (like the kotlin dialect): it reads events (one flat
JSON object per line) from a file argument, applies the same rules the canon
does — via the conformance-proven emitter — and prints the final entity state as
JSON. The fold (state) is what must match the canon; serving is the interpreter's
/ go's job. Fixed + dynamic instances, guard/body/post/conserves and the D54
emit-cascade are supported.
"""
from __future__ import annotations

import ast
import pathlib

from onto.core import expr as E
from onto.core.genome import Genome
from .emit import RUST_HELPERS, emit_body, emit_expr


def _rtype(t: str) -> str:
    return "String" if t == "str" else "i64"


def _lit(ent, f) -> str:
    t = ent.state[f]
    v = ent.init.get(f, "" if t == "str" else 0)
    return f'"{v}".to_string()' if t == "str" else f"{v}i64"


def generate(g: Genome, outdir: str | pathlib.Path, skills_cache=None) -> pathlib.Path:
    out = pathlib.Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "main.rs").write_text(_organism_rs(g), encoding="utf-8")
    return out


def _organism_rs(g: Genome) -> str:
    P: list[str] = []
    add = P.append
    add(f"// Code generated by onto (rust-stdlib dialect) from genome "
        f"'{g.name}'. DO NOT EDIT.")
    add("#![allow(unused, non_snake_case, non_camel_case_types)]")
    add("use std::collections::HashMap;\nuse std::collections::VecDeque;")
    add(RUST_HELPERS)
    add(f"const RETRY_WINDOW: usize = {g.retry_window};\n")

    # ---- a minimal flat-JSON value + line parser (events are flat str/int) ----
    add(r'''#[derive(Clone, Debug)]
enum Val { I(i64), S(String), B(bool) }
impl Val {
    fn as_i(&self) -> i64 { if let Val::I(v) = self { *v } else if let Val::B(b)=self { *b as i64 } else { 0 } }
    fn as_s(&self) -> String { if let Val::S(v) = self { v.clone() } else { String::new() } }
}
fn parse_flat(line: &str) -> HashMap<String, Val> {
    // lenient parser for a FLAT json object {"k": v, ...} (no nested/comma-in-string)
    let mut m = HashMap::new();
    let t = line.trim();
    let t = t.trim_start_matches('{').trim_end_matches('}');
    for part in split_top(t) {
        let part = part.trim();
        if part.is_empty() { continue; }
        let idx = match part.find(':') { Some(i) => i, None => continue };
        let key = part[..idx].trim().trim_matches('"').to_string();
        let raw = part[idx+1..].trim();
        let v = if raw.starts_with('"') {
            Val::S(raw.trim_matches('"').replace("\\\"", "\"").to_string())
        } else if raw == "true" { Val::B(true) }
          else if raw == "false" { Val::B(false) }
          else { Val::I(raw.parse::<i64>().unwrap_or(0)) };
        m.insert(key, v);
    }
    m
}
fn split_top(s: &str) -> Vec<String> {
    let mut out = Vec::new(); let mut cur = String::new(); let mut inq = false;
    let mut prev = ' ';
    for c in s.chars() {
        if c == '"' && prev != '\\' { inq = !inq; }
        if c == ',' && !inq { out.push(cur.clone()); cur.clear(); prev = c; continue; }
        cur.push(c); prev = c;
    }
    if !cur.trim().is_empty() { out.push(cur); }
    out
}
''')

    # ---- entity state structs ----
    for en in sorted(g.entities):
        ent = g.entities[en]
        fields = "\n".join(f"    {f}: {_rtype(ent.state[f])}," for f in sorted(ent.state))
        add(f"#[derive(Clone)]\nstruct {en.capitalize()}State {{\n{fields}\n}}")
        lits = ", ".join(f"{f}: {_lit(ent, f)}" for f in sorted(ent.state))
        add(f"impl {en.capitalize()}State {{ fn init() -> Self {{ Self {{ {lits} }} }} }}\n")

    # ---- typed event structs + decode (like Go's decodeEv<Name>) ----
    for evn in sorted(g.events):
        flds = g.events[evn]
        sfields = "\n".join(f"    {f}: {_rtype(t)}," for f, t in sorted(flds.items()))
        add(f"#[derive(Clone)]\nstruct Ev{evn} {{\n{sfields}\n}}")
        pulls = []
        for f, t in sorted(flds.items()):
            getter = ".as_s()" if t == "str" else ".as_i()"
            default = 'String::new()' if t == "str" else "0i64"
            pulls.append(f'        {f}: m.get("{f}").map(|v| v{getter}).unwrap_or({default}),')
        add(f"fn decode_{evn}(m: &HashMap<String,Val>) -> Ev{evn} {{\n"
            f"    Ev{evn} {{\n" + "\n".join(pulls) + "\n    }\n}\n")

    # ---- rule fns: guard/body/post/conserves (typed ev) ----
    for en in sorted(g.entities):
        ent = g.entities[en]
        stt = f"{en.capitalize()}State"
        for rn in sorted(ent.rules):
            r = ent.rules[rn]
            names = {"s": "s", "ev": "ev"}
            fn = f"{en}_{rn}"
            evt = f"Ev{r.when}"
            if r.guard:
                add(f"fn guard_{fn}(s: &{stt}, ev: &{evt}) -> bool {{ "
                    + emit_expr(E.parse_expr(r.guard), names) + " }")
            body = emit_body(E.parse_body(r.body), names, indent="    ")
            add(f"fn rule_{fn}(s0: &{stt}, ev: &{evt}) -> {stt} {{\n"
                f"    let mut s = s0.clone();\n{body}\n    s\n}}")
            if r.contract.post:
                add(f"fn post_{fn}(s: &{stt}) -> bool {{ "
                    + emit_expr(E.parse_expr(r.contract.post), {"s": "s"}) + " }")
            if r.contract.conserves:
                add(f"fn cons_{fn}(s: &{stt}) -> i64 {{ "
                    + emit_expr(E.parse_expr(r.contract.conserves), {"s": "s"}) + " }")
    add("")

    # ---- organism ----
    st_fields = "\n".join(f"    {en}: HashMap<String, {en.capitalize()}State>,"
                          for en in sorted(g.entities))
    add(f"struct Organism {{\n{st_fields}\n    seen: HashMap<String,bool>,\n"
        f"    seen_q: VecDeque<String>,\n    counters: HashMap<String,i64>,\n}}")

    inits = []
    for en in sorted(g.entities):
        ent = g.entities[en]
        inits.append(f"        let mut {en}: HashMap<String,{en.capitalize()}State> = HashMap::new();")
        if ent.instances != "dynamic":
            for inst in ent.instances:
                inits.append(f'        {en}.insert("{inst}".to_string(), {en.capitalize()}State::init());')
    field_set = ", ".join(sorted(g.entities))
    add("impl Organism {\n    fn new() -> Self {\n" + "\n".join(inits)
        + f"\n        Organism {{ {field_set}, seen: HashMap::new(), "
        f"seen_q: VecDeque::new(), counters: HashMap::new() }}\n    }}")

    # entity lists for aggregates (invariants/queries)
    for en in sorted(g.entities):
        ent = g.entities[en]
        order = (f'let mut v: Vec<{en.capitalize()}State> = self.{en}.values().cloned().collect(); v'
                 if ent.instances == "dynamic"
                 else "vec![" + ", ".join(f'self.{en}["{i}"].clone()' for i in ent.instances) + "]")
        add(f"    fn {en}_list(&self) -> Vec<{en.capitalize()}State> {{ {order} }}")

    lists_names = {en: f"self.{en}_list()" for en in g.entities}
    for name in sorted(g.queries):
        tree = E.parse_expr(g.queries[name])
        ret = "i64" if E.typecheck_expr(tree, g.lists_env_types()) == "int" else "bool"
        add(f"    fn query_{name}(&self) -> {ret} {{ "
            + emit_expr(tree, lists_names) + " }")

    # dedup
    add("""    fn dedup(&mut self, id: &str) -> bool {
        if self.seen.contains_key(id) { return true; }
        self.seen.insert(id.to_string(), true);
        self.seen_q.push_back(id.to_string());
        while self.seen_q.len() > RETRY_WINDOW {
            if let Some(old) = self.seen_q.pop_front() { self.seen.remove(&old); }
        }
        false
    }""")

    # dispatch + fire per event
    fire_arms = []
    for evn in sorted(g.events):
        arms = []
        for en, ent in g.entities.items():
            for rn, r in ent.rules.items():
                if r.when != evn:
                    continue
                fn = f"{en}_{rn}"
                key = g.key_field(en)
                cap = en.capitalize()
                grd = (f"                if !guard_{fn}(st, &ev) {{ break 'arm; }}\n"
                       if r.guard else "")
                post_chk = ""
                if r.contract.post:
                    post_chk += (f"                if !post_{fn}(&next) {{ "
                                 f"*self.counters.entry(\"rejected\".into()).or_insert(0)+=1; break 'arm; }}\n")
                if r.contract.conserves:
                    post_chk += (f"                if cons_{fn}(st) != cons_{fn}(&next) {{ "
                                 f"*self.counters.entry(\"rejected\".into()).or_insert(0)+=1; break 'arm; }}\n")
                if ent.instances == "dynamic":
                    ensure = (f'                let inst = evm.get("{key}").map(|v| v.as_s()).unwrap_or_default();\n'
                              f"                if inst.is_empty() {{ break 'arm; }}\n"
                              f"                self.{en}.entry(inst.clone()).or_insert_with({cap}State::init);\n"
                              f"                let st = self.{en}.get(&inst).unwrap();\n")
                else:
                    ensure = (f'                let inst = evm.get("{key}").map(|v| v.as_s()).unwrap_or_default();\n'
                              f"                if !self.{en}.contains_key(&inst) {{ break 'arm; }}\n"
                              f"                let st = self.{en}.get(&inst).unwrap();\n")
                emits = ""
                for k_e, em in enumerate(r.emit):
                    names_e = {"s": "&next", "ev": "ev"}
                    flds = []
                    for f, src in em.fields.items():
                        printed = emit_expr(E.parse_expr(src), {"s": "next", "ev": "ev"})
                        ftype = g.events[em.event][f]
                        val = (f'Val::S({printed})' if ftype == "str" else f'Val::I({printed})')
                        # translate ev.<x>/next.<x> field access into map/struct reads
                        flds.append(f'                    child.insert("{f}".to_string(), {val});')
                    cond = (emit_expr(E.parse_expr(em.when), {"s": "next", "ev": "ev"})
                            if em.when else "true")
                    emits += (f'                if {cond} {{\n'
                              f'                    let mut child: HashMap<String,Val> = HashMap::new();\n'
                              f'                    child.insert("type".to_string(), Val::S("{em.event}".to_string()));\n'
                              + "\n".join(flds) + "\n"
                              f'                    self.dispatch(&child, depth+1);\n'
                              f'                }}\n')
                arms.append(
                    f"            'arm: {{\n{ensure}{grd}"
                    f"                let next = rule_{fn}(st, &ev);\n{post_chk}"
                    f"                self.{en}.insert(inst.clone(), next.clone());\n"
                    f"                *self.counters.entry(\"applied\".into()).or_insert(0)+=1;\n"
                    f"{emits}            }}")
        arms_s = "\n".join(arms)
        fire_arms.append(f'        if typ == "{evn}" {{\n            let ev = decode_{evn}(&evm);\n{arms_s}\n        }}')
    fire_body = "\n".join(fire_arms)
    add(f"""    fn dispatch(&mut self, evm: &HashMap<String,Val>, depth: i64) {{
        if depth > 8 {{ return; }}
        let evm = evm.clone();
        let typ = evm.get("type").map(|v| v.as_s()).unwrap_or_default();
{fire_body}
    }}
    fn handle(&mut self, evm: HashMap<String,Val>) {{
        let id = evm.get("id").map(|v| v.as_s()).unwrap_or_default();
        if !id.is_empty() && self.dedup(&id) {{ return; }}
        self.dispatch(&evm, 0);
    }}""")

    # print final state as JSON
    # ---- dump the final fold as JSON: {"en":{"inst":{"field":v,...},...},...}
    dump_lines = ['    fn dump(&self) -> String {',
                  '        let mut out = String::from("{");']
    for i, en in enumerate(sorted(g.entities)):
        ent = g.entities[en]
        parts = []
        for f in sorted(ent.state):
            if ent.state[f] == "str":
                parts.append(f'format!("\\"{f}\\":\\"{{}}\\"", st.{f})')
            else:
                parts.append(f'format!("\\"{f}\\":{{}}", st.{f})')
        fields_expr = "[" + ", ".join(parts) + "].join(\",\")"
        if i > 0:
            dump_lines.append('        out.push_str(",");')
        dump_lines.append(f'        out.push_str("\\"{en}\\":{{");')
        dump_lines.append(f'        let mut keys: Vec<&String> = self.{en}.keys().collect(); keys.sort();')
        dump_lines.append('        for (j,k) in keys.iter().enumerate() {')
        dump_lines.append(f'            let st = &self.{en}[*k];')
        dump_lines.append('            if j>0 { out.push_str(","); }')
        dump_lines.append(f'            out.push_str(&format!("\\"{{}}\\":{{{{{{}}}}}}", k, {fields_expr}));')
        dump_lines.append('        }')
        dump_lines.append('        out.push_str("}");')
    dump_lines.append('        out.push_str("}");')
    dump_lines.append('        out')
    dump_lines.append('    }')
    dump_lines.append('}')
    add("\n".join(dump_lines))

    # main
    add(r'''fn main() {
    let args: Vec<String> = std::env::args().collect();
    let mut org = Organism::new();
    if args.len() > 1 {
        let text = std::fs::read_to_string(&args[1]).unwrap_or_default();
        for line in text.lines() {
            if line.trim().is_empty() { continue; }
            org.handle(parse_flat(line));
        }
    }
    println!("{}", org.dump());
}''')
    return "\n".join(P)
