# -*- coding: utf-8 -*-
"""kotlin-stdlib: the organism skeleton, printed deterministically from the
genome reference (rung 0 of the ladder = the printer).

The phenotype is a single Main.kt that computes the FOLD: read events (a simple
tab line format — the batch port's encoding), apply the genome's rules with the
reference semantics (id-dedup, key routing, dynamic birth BEFORE guard, guard,
body), and print the full state snapshot. Transport (HTTP/queue) is the D88
ports layer, orthogonal — this file certifies the LANGUAGE via fold-parity.

Byte-for-byte determinism: sorted traversals only, no timestamps. Zero deps
outside the JDK/Kotlin stdlib.
"""
from __future__ import annotations

import pathlib

from onto.core import expr as E
from onto.core.genome import Genome
from onto.dialects.kotlin_stdlib.emit import emit_body, emit_expr, ktlit, kttype


def _cls(en: str) -> str:
    return "".join(w.capitalize() for w in en.split("_")) + "State"


def _default_channels():
    return [{"driver": "file", "direction": "in", "codec": "json"}]


def generate(g: Genome, outdir: str | pathlib.Path,
             skills_cache=None, channels=None) -> pathlib.Path:
    out = pathlib.Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "Main.kt").write_text(_main_kt(g, channels or _default_channels()),
                                 encoding="utf-8")
    return out


def _main_kt(g: Genome, channels: list) -> str:
    P: list[str] = []
    add = P.append
    add(f"// Code generated by onto (kotlin-stdlib dialect) from genome "
        f"'{g.name}'. DO NOT EDIT.")
    add("import java.io.File\n")

    # ---- state data classes (mutable copy semantics via var + copy())
    for en in sorted(g.entities):
        ent = g.entities[en]
        fields = ", ".join(
            f"var {f}: {kttype(ent.state[f])} = {ktlit(ent.init.get(f, '' if ent.state[f]=='str' else 0), ent.state[f])}"
            for f in sorted(ent.state))
        add(f"data class {_cls(en)}({fields})")

    # ---- event data classes + decoders
    for evn in sorted(g.events):
        ev = g.events[evn]
        fields = ", ".join(f"val {f}: {kttype(t)}" for f, t in sorted(ev.items()))
        add(f"data class Ev{evn}({fields})")
        args = ", ".join(
            (f'{f} = m["{f}"]!!' if t == "str" else f'{f} = m["{f}"]!!.toLong()')
            for f, t in sorted(ev.items()))
        add(f"fun decode{evn}(m: Map<String, String>): Ev{evn} = Ev{evn}({args})")
    add("")

    # ---- rules: guard + body, printed from the reference
    for en in sorted(g.entities):
        ent = g.entities[en]
        for rn in sorted(ent.rules):
            r = ent.rules[rn]
            names = {"s": "s", "ev": "ev"}
            st, evt = _cls(en), f"Ev{r.when}"
            if r.guard:
                add(f"fun guard_{en}_{rn}(s: {st}, ev: {evt}): Boolean = "
                    + emit_expr(E.parse_expr(r.guard), names))
            body = emit_body(E.parse_body(r.body), names, "    ")
            add(f"fun rule_{en}_{rn}(s0: {st}, ev: {evt}): {st} {{\n"
                f"    val s = s0.copy()\n{body}\n    return s\n}}")
    add("")

    # ---- main: fold driver
    add(_kt_organism(g))
    add(_kt_doors(g, channels))
    return "\n".join(P) + "\n"


def _kt_parseflat() -> str:
    return r"""fun parseFlat(line: String): HashMap<String, String> {
    val m = HashMap<String, String>()
    var t = line.trim()
    if (t.startsWith("{")) t = t.substring(1)
    if (t.endsWith("}")) t = t.substring(0, t.length - 1)
    var inq = false
    val cur = StringBuilder()
    val parts = ArrayList<String>()
    for (c in t) {
        if (c == '"') inq = !inq
        if (c == ',' && !inq) { parts.add(cur.toString()); cur.setLength(0) } else cur.append(c)
    }
    if (cur.isNotBlank()) parts.add(cur.toString())
    for (p in parts) {
        val idx = p.indexOf(':'); if (idx < 0) continue
        val k = p.substring(0, idx).trim().trim('"')
        var v = p.substring(idx + 1).trim()
        if (v.startsWith("\"")) v = v.trim('"')
        m[k] = v
    }
    return m
}
"""


def _kt_organism(g) -> str:
    L = [_kt_parseflat(), "class Organism {"]
    # state maps + fixed instances
    for en in sorted(g.entities):
        ent = g.entities[en]
        L.append(f"    val {en} = LinkedHashMap<String, {_cls(en)}>()")
    L.append("    val seen = HashSet<String>()")
    L.append("    init {")
    for en in sorted(g.entities):
        ent = g.entities[en]
        if ent.instances != "dynamic":
            for inst in ent.instances:
                lits = ", ".join(
                    f"{f} = {ktlit(ent.init.get(f, '' if ent.state[f]=='str' else 0), ent.state[f])}"
                    for f in sorted(ent.state))
                L.append(f'        {en}["{inst}"] = {_cls(en)}({lits})')
    L.append("    }")
    # handle(m)
    L.append("    fun handle(m: Map<String, String>) {")
    L.append('        val id = m["id"] ?: ""')
    L.append('        val type = m["type"] ?: ""')
    L.append("        if (id.isNotEmpty() && !seen.add(id)) return")
    L.append("        when (type) {")
    for evn in sorted(g.events):
        matching = [(en, rn) for en in sorted(g.entities)
                    for rn in sorted(g.entities[en].rules)
                    if g.entities[en].rules[rn].when == evn]
        if not matching:
            continue
        L.append(f'            "{evn}" -> {{')
        L.append(f"                val ev = decode{evn}(m)")
        for en, rn in matching:
            keyf = g.key_field(en)
            init_lits = ", ".join(
                f"{f} = {ktlit(g.entities[en].init.get(f, '' if g.entities[en].state[f]=='str' else 0), g.entities[en].state[f])}"
                for f in sorted(g.entities[en].state))
            guarded = g.entities[en].rules[rn].guard
            cond = f"guard_{en}_{rn}(s, ev)" if guarded else "true"
            L.append("                run {")
            L.append(f'                    val inst = m["{keyf}"] ?: ""')
            L.append("                    if (inst.isNotEmpty()) {")
            L.append(f'                        val s = {en}.getOrPut(inst) {{ {_cls(en)}({init_lits}) }}')
            L.append(f'                        if ({cond}) {{ {en}[inst] = rule_{en}_{rn}(s, ev) }}')
            L.append("                    }")
            L.append("                }")
        L.append("            }")
    L.append("        }")
    L.append("    }")
    # dumpJson()
    L.append("    fun dumpJson(): String {")
    L.append('        val b = StringBuilder("{")')
    for i, en in enumerate(sorted(g.entities)):
        ent = g.entities[en]
        if i > 0:
            L.append('        b.append(",")')
        L.append(f'        b.append("\\"{en}\\":{{")')
        L.append(f"        var first{i} = true")
        L.append(f"        for (inst in {en}.keys.sorted()) {{")
        L.append(f"            if (!first{i}) b.append(\",\"); first{i} = false")
        L.append(f"            val s = {en}[inst]!!")
        flds = []
        for f in sorted(ent.state):
            if ent.state[f] == "str":
                flds.append(f'\\"{f}\\":\\"$' + '{s.' + f + '}\\"')
            else:
                flds.append(f'\\"{f}\\":$' + '{s.' + f + '}')
        inner = ",".join(flds)
        L.append(f'            b.append("\\"$inst\\":{{{inner}}}")')
        L.append("        }")
        L.append('        b.append("}")')
    L.append('        b.append("}")')
    L.append("        return b.toString()")
    L.append("    }")
    # stateJson(en, inst)
    L.append("    fun stateJson(en: String, inst: String): String? {")
    for en in sorted(g.entities):
        ent = g.entities[en]
        flds = []
        for f in sorted(ent.state):
            if ent.state[f] == "str":
                flds.append(f'\\"{f}\\":\\"$' + '{s.' + f + '}\\"')
            else:
                flds.append(f'\\"{f}\\":$' + '{s.' + f + '}')
        inner = ",".join(flds)
        L.append(f'        if (en == "{en}") {{ val s = {en}[inst] ?: return null; return "{{{inner}}}" }}')
    L.append("        return null")
    L.append("    }")
    L.append("}")
    return "\n".join(L)


def _kt_doors(g, channels) -> str:
    ins = [c for c in (channels or []) if c.get("direction", "in") == "in"]
    driver = (ins[0] if ins else {}).get("driver", "file")
    if driver in ("file", "stdio"):
        src = ("File(args[0]).readLines()" if driver == "file"
               else "generateSequence(::readLine).toList()")
        return ("fun main(args: Array<String>) {\n"
                "    val org = Organism()\n"
                f"    for (line in {src}) {{\n"
                "        if (line.isNotBlank()) org.handle(parseFlat(line))\n"
                "    }\n"
                "    println(org.dumpJson())\n"
                "}\n")
    if driver == "http":
        return r"""fun main(args: Array<String>) {
    var port = 8610
    var i = 0
    while (i < args.size) { if (args[i] == "--port" && i + 1 < args.size) { port = args[i + 1].toInt() }; i++ }
    val org = Organism()
    val server = com.sun.net.httpserver.HttpServer.create(java.net.InetSocketAddress("127.0.0.1", port), 0)
    server.createContext("/") { ex ->
        val method = ex.requestMethod
        val path = ex.requestURI.path
        val body = ex.requestBody.readBytes().toString(Charsets.UTF_8)
        val (code, resp) = route(org, method, path, body)
        val bytes = resp.toByteArray()
        ex.responseHeaders.add("Content-Type", "application/json")
        ex.sendResponseHeaders(code, bytes.size.toLong())
        ex.responseBody.use { it.write(bytes) }
    }
    server.executor = null
    System.err.println("kotlin-stdlib organism (HTTP door) on 127.0.0.1:$port")
    server.start()
}

fun route(org: Organism, method: String, path: String, body: String): Pair<Int, String> {
    if (method == "POST" && path == "/event") { org.handle(parseFlat(body)); return Pair(200, "{\"status\":\"applied\"}") }
    if (method == "GET" && path == "/health") return Pair(200, "{\"ok\":true}")
    if (method == "GET" && path == "/dump") return Pair(200, org.dumpJson())
    val segs = path.trim('/').split("/")
    if (method == "GET" && segs.size == 3 && segs[0] == "state") {
        val js = org.stateJson(segs[1], segs[2]) ?: return Pair(404, "{\"error\":\"no such state\"}")
        return Pair(200, js)
    }
    return Pair(404, "{\"error\":\"unknown route\"}")
}
"""
    # tcp
    return r"""fun main(args: Array<String>) {
    var port = 8610
    var i = 0
    while (i < args.size) { if (args[i] == "--port" && i + 1 < args.size) { port = args[i + 1].toInt() }; i++ }
    val org = Organism()
    val server = java.net.ServerSocket()
    server.reuseAddress = true
    server.bind(java.net.InetSocketAddress("127.0.0.1", port))
    System.err.println("kotlin-stdlib organism (TCP door) on 127.0.0.1:$port")
    while (true) {
        val conn = server.accept()
        val reader = conn.getInputStream().bufferedReader()
        val writer = conn.getOutputStream().bufferedWriter()
        var line = reader.readLine()
        while (line != null) {
            val t = line.trim()
            val resp = when {
                t.isEmpty() -> ""
                t == "?dump" -> org.dumpJson()
                t.startsWith("?state/") -> { val sg = t.substring(7).split("/"); if (sg.size == 2) (org.stateJson(sg[0], sg[1]) ?: "null") else "null" }
                else -> { org.handle(parseFlat(t)); "{\"status\":\"applied\"}" }
            }
            if (resp.isNotEmpty()) { writer.write(resp); writer.write("\n"); writer.flush() }
            line = reader.readLine()
        }
        conn.close()
    }
}
"""


#__AFTER__
