# -*- coding: utf-8 -*-
"""kotlin-stdlib: the organism skeleton, printed deterministically from the
genome reference (rung 0 of the ladder = the printer).

The phenotype is a single Main.kt that computes the FOLD: read events (a simple
tab line format — the batch port's encoding), apply the genome's rules with the
reference semantics (id-dedup, key routing, dynamic birth BEFORE guard, guard,
body), and print the full state snapshot. Transport (HTTP/queue) is the D88
ports layer, orthogonal — this file certifies the LANGUAGE via fold-parity.

Byte-for-byte determinism: sorted traversals only, no timestamps. Zero deps
outside the JDK/Kotlin stdlib.
"""
from __future__ import annotations

import pathlib

from onto.core import expr as E
from onto.core.genome import Genome
from onto.dialects.kotlin_stdlib.emit import emit_body, emit_expr, ktlit, kttype


def _cls(en: str) -> str:
    return "".join(w.capitalize() for w in en.split("_")) + "State"


def generate(g: Genome, outdir: str | pathlib.Path,
             skills_cache=None) -> pathlib.Path:
    out = pathlib.Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "Main.kt").write_text(_main_kt(g), encoding="utf-8")
    return out


def _main_kt(g: Genome) -> str:
    P: list[str] = []
    add = P.append
    add(f"// Code generated by onto (kotlin-stdlib dialect) from genome "
        f"'{g.name}'. DO NOT EDIT.")
    add("import java.io.File\n")

    # ---- state data classes (mutable copy semantics via var + copy())
    for en in sorted(g.entities):
        ent = g.entities[en]
        fields = ", ".join(
            f"var {f}: {kttype(ent.state[f])} = {ktlit(ent.init.get(f, '' if ent.state[f]=='str' else 0), ent.state[f])}"
            for f in sorted(ent.state))
        add(f"data class {_cls(en)}({fields})")

    # ---- event data classes + decoders
    for evn in sorted(g.events):
        ev = g.events[evn]
        fields = ", ".join(f"val {f}: {kttype(t)}" for f, t in sorted(ev.items()))
        add(f"data class Ev{evn}({fields})")
        args = ", ".join(
            (f'{f} = m["{f}"]!!' if t == "str" else f'{f} = m["{f}"]!!.toLong()')
            for f, t in sorted(ev.items()))
        add(f"fun decode{evn}(m: Map<String, String>): Ev{evn} = Ev{evn}({args})")
    add("")

    # ---- rules: guard + body, printed from the reference
    for en in sorted(g.entities):
        ent = g.entities[en]
        for rn in sorted(ent.rules):
            r = ent.rules[rn]
            names = {"s": "s", "ev": "ev"}
            st, evt = _cls(en), f"Ev{r.when}"
            if r.guard:
                add(f"fun guard_{en}_{rn}(s: {st}, ev: {evt}): Boolean = "
                    + emit_expr(E.parse_expr(r.guard), names))
            body = emit_body(E.parse_body(r.body), names, "    ")
            add(f"fun rule_{en}_{rn}(s0: {st}, ev: {evt}): {st} {{\n"
                f"    val s = s0.copy()\n{body}\n    return s\n}}")
    add("")

    # ---- main: fold driver
    add("fun main(args: Array<String>) {")
    for en in sorted(g.entities):
        ent = g.entities[en]
        add(f"    val {en} = LinkedHashMap<String, {_cls(en)}>()")
        if ent.instances != "dynamic":
            for inst in ent.instances:
                lits = ", ".join(
                    f"{f} = {ktlit(ent.init.get(f, '' if ent.state[f]=='str' else 0), ent.state[f])}"
                    for f in sorted(ent.state))
                add(f'    {en}["{inst}"] = {_cls(en)}({lits})')
    add("    val seen = HashSet<String>()")
    add("    for (line in File(args[0]).readLines()) {")
    add("        if (line.isEmpty()) continue")
    add('        val parts = line.split("\\t")')
    add("        val id = parts[0]; val type = parts[1]")
    add("        if (id.isEmpty()) continue")
    add("        val m = HashMap<String, String>()")
    add("        for (i in 2 until parts.size) {")
    add('            val kv = parts[i].split("=", limit = 2)')
    add("            m[kv[0]] = kv[1]")
    add("        }")
    add("        if (!seen.add(id)) continue   // id dedup")
    add("        when (type) {")
    # dispatch: per event type, every (entity, rule) whose when == type
    for evn in sorted(g.events):
        matching = [(en, rn)
                    for en in sorted(g.entities)
                    for rn in sorted(g.entities[en].rules)
                    if g.entities[en].rules[rn].when == evn]
        if not matching:
            continue
        add(f'            "{evn}" -> {{')
        add(f"                val ev = decode{evn}(m)")
        for en, rn in matching:
            keyf = g.key_field(en)
            init_lits = ", ".join(
                f"{f} = {ktlit(g.entities[en].init.get(f, '' if g.entities[en].state[f]=='str' else 0), g.entities[en].state[f])}"
                for f in sorted(g.entities[en].state))
            guarded = g.entities[en].rules[rn].guard
            cond = f"guard_{en}_{rn}(s, ev)" if guarded else "true"
            add(f'                run {{')
            add(f'                    val inst = m["{keyf}"] ?: ""')
            add(f'                    if (inst.isNotEmpty()) {{')
            add(f'                        val s = {en}.getOrPut(inst) {{ {_cls(en)}({init_lits}) }}')
            add(f'                        if ({cond}) {{ {en}[inst] = rule_{en}_{rn}(s, ev) }}')
            add(f'                    }}')
            add(f'                }}')
        add("            }")
    add("        }")
    add("    }")
    # ---- snapshot: entity -> instance -> {field: value}, all sorted
    add("    val out = StringBuilder()")
    for en in sorted(g.entities):
        ent = g.entities[en]
        add(f"    for (inst in {en}.keys.sorted()) {{")
        add(f"        val s = {en}[inst]!!")
        parts = [f'"{en}"', "inst"]
        for f in sorted(ent.state):
            parts.append(f'"{f}=" + s.{f}')
        add('        out.append(' + ' + "\\t" + '.join(parts) + ' + "\\n")')
        add("    }")
    add("    print(out)")
    add("}")
    return "\n".join(P) + "\n"
