# -*- coding: utf-8 -*-
"""go-stdlib: the organism skeleton — the WHOLE phenotype is printed
deterministically from the genome reference (D27: rung 0 of the ladder = the
printer; the SLM is for skills).

Parity with the core: the same HTTP endpoints, the same events.jsonl format, the
same windowed dedup, the same D25 semantics — ONE judge must be green on both.
Byte-for-byte determinism: sorted traversals only, no timestamps.
"""
from __future__ import annotations

import pathlib

from onto.core import expr as E
from onto.core.genome import Genome
from onto.dialects.go_stdlib.emit import GO_HELPERS, emit_body, emit_expr, goname


def _gotype(t: str) -> str:
    return "string" if t == "str" else "int64"


def _default_channels() -> list[dict]:
    return [{"driver": "http", "direction": "in", "codec": "json"}]


def generate(g: Genome, outdir: str | pathlib.Path,
             skills_cache=None, channels=None) -> pathlib.Path:
    out = pathlib.Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    (out / "go.mod").write_text(f"module {g.name}_organism\n\ngo 1.22\n")
    (out / "main.go").write_text(_main_go(g, channels or _default_channels()))
    return out


def _main_go(g: Genome, channels: list[dict]) -> str:
    ins = [c for c in channels if c.get("direction", "in") == "in"]
    driver = (ins[0] if ins else {}).get("driver", "http")
    codec = (ins[0] if ins else {}).get("codec", "json")
    P: list[str] = []
    add = P.append
    add("// Code generated by onto (go-stdlib dialect) from genome "
        f"'{g.name}'. DO NOT EDIT.\npackage main\n")
    base = ['"bufio"', '"encoding/json"', '"fmt"', '"os"',
            '"path/filepath"', '"sort"', '"strings"', '"sync"']
    if driver == "http":
        base += ['"bytes"', '"io"', '"net/http"', '"time"']
    elif driver == "tcp":
        base += ['"net"']
    if codec == "kv":
        base += ['"strconv"']
    add("import (\n" + "".join(f"\t{i}\n" for i in sorted(base)) + ")\n")
    add(GO_HELPERS)
    add(f"const retryWindow = {g.retry_window}\n")

    # ---- state types and events
    def _golit(ent, f):
        v = ent.init.get(f, "" if ent.state[f] == "str" else 0)
        return f'"{v}"' if ent.state[f] == "str" else str(v)

    for en in sorted(g.entities):
        ent = g.entities[en]
        fields = "\n".join(
            f"\t{goname(f)} {_gotype(ent.state[f])} `json:\"{f}\"`"
            for f in sorted(ent.state))
        add(f"type {goname(en)}State struct {{\n{fields}\n}}\n")
    for evn in sorted(g.events):
        fields = "\n".join(
            f"\t{goname(f)} {_gotype(t)} `json:\"{f}\"`"
            for f, t in sorted(g.events[evn].items()))
        add(f"type Ev{evn} struct {{\n{fields}\n}}\n")
        conv = []
        for f, t in sorted(g.events[evn].items()):
            if t == "str":
                conv.append(f'\tif v, ok := m["{f}"].(string); ok {{ ev.{goname(f)} = v }} else {{ return ev, fmt.Errorf("missing event fields: [{f}]") }}')
            else:
                conv.append(f'\tif v, ok := m["{f}"].(float64); ok {{ ev.{goname(f)} = int64(v) }} else {{ return ev, fmt.Errorf("missing event fields: [{f}]") }}')
        add(f"func decodeEv{evn}(m map[string]any) (Ev{evn}, error) {{\n"
            f"\tvar ev Ev{evn}\n" + "\n".join(conv) + "\n\treturn ev, nil\n}\n")

    # ---- rules: guard/body/post/conserves — printed from the reference
    for en in sorted(g.entities):
        ent = g.entities[en]
        st_t = f"{goname(en)}State"
        for rn in sorted(ent.rules):
            r = ent.rules[rn]
            ev_t = f"Ev{r.when}"
            names = {"s": "s", "ev": "ev"}
            fn = goname(en) + goname(rn)
            if r.guard:
                add(f"func guard{fn}(s {st_t}, ev {ev_t}) bool {{\n\treturn "
                    + emit_expr(E.parse_expr(r.guard), names) + "\n}\n")
            add(f"func rule{fn}(s {st_t}, ev {ev_t}) {st_t} {{\n"
                + emit_body(E.parse_body(r.body), names) + "\n\treturn s\n}\n")
            if r.contract.post:
                add(f"func post{fn}(s {st_t}) bool {{\n\treturn "
                    + emit_expr(E.parse_expr(r.contract.post), {"s": "s"}) + "\n}\n")
            if r.contract.conserves:
                add(f"func conserves{fn}(s {st_t}) int64 {{\n\treturn "
                    + emit_expr(E.parse_expr(r.contract.conserves), {"s": "s"}) + "\n}\n")

    # ---- organism
    st_fields = "\n".join(
        f"\t{goname(en)} map[string]*{goname(en)}State" for en in sorted(g.entities))
    add(f"""type Organism struct {{
\tmu sync.Mutex
{st_fields}
\tseen map[string]bool
\tseenQ []string
\tcounters map[string]int64
\tdataDir string
\treplaying bool
\toutEvents []string
}}
""")
    inits = []
    for en in sorted(g.entities):
        ent = g.entities[en]
        inits.append(f"\to.{goname(en)} = map[string]*{goname(en)}State{{}}")
        if ent.instances != "dynamic":                     # D51: dynamic entities start empty
            for inst in ent.instances:
                lits = ", ".join(f"{goname(f)}: {_golit(ent, f)}" for f in sorted(ent.state))
                inits.append(f'\to.{goname(en)}["{inst}"] = &{goname(en)}State{{{lits}}}')
    add("func newOrganism(dataDir string) *Organism {\n\to := &Organism{}\n"
        + "\n".join(inits) + "\n"
        + '\to.seen = map[string]bool{}\n\to.counters = map[string]int64{'
        + '"applied": 0, "dup": 0, "noop": 0, "rejected": 0, '
        + '"unknown_instance": 0, "invariant_violations": 0}\n'
        + "\to.dataDir = dataDir\n\treturn o\n}\n")

    # lists for aggregates (the genome's instance order — as in the core)
    for en in sorted(g.entities):
        ent = g.entities[en]
        if ent.instances == "dynamic":
            add(f"func (o *Organism) {en}List() []{goname(en)}State {{\n"
                f"\tout := []{goname(en)}State{{}}\n"
                f"\tfor _, v := range o.{goname(en)} {{ out = append(out, *v) }}\n"
                f"\treturn out\n}}\n")
        else:
            items = "\n".join(f'\t\t*o.{goname(en)}["{i}"],' for i in ent.instances)
            add(f"func (o *Organism) {en}List() []{goname(en)}State {{\n"
                f"\treturn []{goname(en)}State{{\n{items}\n\t}}\n}}\n")

    lists_names = {en: f"o.{en}List()" for en in g.entities}

    # invariants and queries — printed from the reference
    for name in sorted(g.invariants):
        add(f"func (o *Organism) invariant{goname(name)}() bool {{\n\treturn "
            + emit_expr(E.parse_expr(g.invariants[name]), lists_names) + "\n}\n")
    for name in sorted(g.queries):
        tree = E.parse_expr(g.queries[name])
        ret = "int64" if E.typecheck_expr(tree, g.lists_env_types()) == "int" else "bool"
        add(f"func (o *Organism) query{goname(name)}() {ret} {{\n\treturn "
            + emit_expr(tree, lists_names) + "\n}\n")
    qcases = "\n".join(
        f'\tcase "{n}":\n\t\treturn o.query{goname(n)}(), true'
        for n in sorted(g.queries))
    add(f"func (o *Organism) query(name string) (any, bool) {{\n\tswitch name {{\n{qcases}\n\t}}\n\treturn nil, false\n}}\n")

    # ---- dedup, ledger, handle
    add("""func (o *Organism) dedup(id string) bool {
\tif o.seen[id] {
\t\treturn true
\t}
\to.seen[id] = true
\to.seenQ = append(o.seenQ, id)
\tfor len(o.seenQ) > retryWindow {
\t\tdelete(o.seen, o.seenQ[0])
\t\to.seenQ = o.seenQ[1:]
\t}
\treturn false
}

func (o *Organism) ledger(kind string, payload map[string]any) {
\tif o.replaying || o.dataDir == "" {
\t\treturn
\t}
\tpayload["kind"] = kind
\tb, _ := json.Marshal(payload)
\tf, err := os.OpenFile(filepath.Join(o.dataDir, "ledger.jsonl"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
\tif err == nil {
\t\tf.Write(append(b, '\\n'))
\t\tf.Close()
\t}
}

func (o *Organism) appendLog(raw []byte) {
\tif o.replaying || o.dataDir == "" {
\t\treturn
\t}
\tf, err := os.OpenFile(filepath.Join(o.dataDir, "events.jsonl"), os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
\tif err == nil {
\t\tf.Write(append(raw, '\\n'))
\t\tf.Sync()
\t\tf.Close()
\t}
}
""")
    # fan-out: over entities in the genome's declaration order (parity with the core)
    fire = []
    for evn in sorted(g.events):
        arms = []
        for en, ent in g.entities.items():          # genome order!
            for rn, r in ent.rules.items():
                if r.when != evn:
                    continue
                fn = goname(en) + goname(rn)
                key = g.key_field(en)
                grd = (f"\t\tif !guard{fn}(*st, ev) {{\n"
                       f"\t\t\to.counters[\"noop\"]++\n"
                       f"\t\t\toutcomes[\"{en}.{rn}\"] = \"noop(guard)\"\n"
                       f"\t\t\treturn\n\t\t}}\n") if r.guard else ""
                post_chk = ""
                if r.contract.post:
                    post_chk += (f"\t\tif !post{fn}(next) {{\n"
                                 f"\t\t\to.counters[\"rejected\"]++\n"
                                 f"\t\t\to.ledger(\"contract_post\", map[string]any{{\"entity\": \"{en}\", \"rule\": \"{rn}\", \"instance\": inst, \"event\": id}})\n"
                                 f"\t\t\toutcomes[\"{en}.{rn}\"] = \"rejected(post)\"\n"
                                 f"\t\t\treturn\n\t\t}}\n")
                if r.contract.conserves:
                    post_chk += (f"\t\tif conserves{fn}(*st) != conserves{fn}(next) {{\n"
                                 f"\t\t\to.counters[\"rejected\"]++\n"
                                 f"\t\t\to.ledger(\"contract_conserves\", map[string]any{{\"entity\": \"{en}\", \"rule\": \"{rn}\", \"instance\": inst, \"event\": id}})\n"
                                 f"\t\t\toutcomes[\"{en}.{rn}\"] = \"rejected(conserves)\"\n"
                                 f"\t\t\treturn\n\t\t}}\n")
                if ent.instances == "dynamic":
                    init_lits = ", ".join(f"{goname(f)}: {_golit(ent, f)}"
                                          for f in sorted(ent.state))
                    miss = (f"\t\tif !ok {{\n"
                            f"\t\t\tif inst == \"\" {{\n"
                            f"\t\t\t\to.counters[\"unknown_instance\"]++\n"
                            f"\t\t\t\toutcomes[\"{en}.{rn}\"] = \"unknown-instance:\"\n"
                            f"\t\t\t\treturn\n\t\t\t}}\n"
                            f"\t\t\tst = &{goname(en)}State{{{init_lits}}}\n"
                            f"\t\t\to.{goname(en)}[inst] = st\n\t\t}}\n")
                else:
                    miss = (f"\t\tif !ok {{\n"
                            f"\t\t\to.counters[\"unknown_instance\"]++\n"
                            f"\t\t\toutcomes[\"{en}.{rn}\"] = \"unknown-instance:\" + inst\n"
                            f"\t\t\treturn\n\t\t}}\n")
                emits = ""
                for k_e, em in enumerate(r.emit):
                    names_e = {"s": "next", "ev": "ev"}
                    flds = []
                    for f, src in em.fields.items():
                        ftype = g.events[em.event][f]
                        printed = emit_expr(E.parse_expr(src), names_e)
                        flds.append(f'"{f}": ' + (printed if ftype == "str"
                                                  else f"float64({printed})"))
                    cond = (emit_expr(E.parse_expr(em.when), names_e)
                            if em.when else "true")
                    emits += (f"\t\tif {cond} {{\n"
                              f"\t\t\t_child{k_e} := map[string]any{{\"type\": \"{em.event}\", "
                              + ", ".join(flds) + "}\n"
                              f"\t\t\tif _b, _e := json.Marshal(_child{k_e}); _e == nil {{ o.outEvents = append(o.outEvents, string(_b)) }}\n"
                              f"\t\t\to.dispatch(\"{em.event}\", _child{k_e}, id+\":p{k_e}\", outcomes, depth+1)\n"
                              f"\t\t}}\n")
                arms.append(f"""\tfunc() {{
\t\tinst, _ := m["{key}"].(string)
\t\tst, ok := o.{goname(en)}[inst]
{miss}{grd}\t\tnext := rule{fn}(*st, ev)
{post_chk}\t\t*st = next
\t\toutcomes["{en}.{rn}"] = "applied"
{emits}\t}}()""")
        arms_s = "\n".join(arms) if arms else "\t_ = ev"
        fire.append(f"""func (o *Organism) fire{evn}(m map[string]any, id string, outcomes map[string]string, depth int) error {{
\tev, err := decodeEv{evn}(m)
\tif err != nil {{
\t\treturn err
\t}}
\t_ = depth
{arms_s}
\treturn nil
}}""")
    add("\n\n".join(fire) + "\n")

    inv_checks = "\n".join(
        f"\tif !o.invariant{goname(n)}() {{\n"
        f"\t\to.counters[\"invariant_violations\"]++\n"
        f"\t\to.ledger(\"invariant_violation\", map[string]any{{\"invariant\": \"{n}\", \"event\": id}})\n\t}}"
        for n in sorted(g.invariants))
    evdispatch = "\n".join(
        f'\tcase "{evn}":\n\t\terr = o.fire{evn}(m, id, outcomes, depth)'
        for evn in sorted(g.events))
    add(f"""func (o *Organism) dispatch(typ string, m map[string]any, id string, outcomes map[string]string, depth int) error {{
\tif depth > 8 {{
\t\to.ledger("cascade_overflow", map[string]any{{"event": id, "type": typ}})
\t\toutcomes["cascade:"+typ] = "overflow"
\t\treturn nil
\t}}
\tvar err error
\tswitch typ {{
{evdispatch}
\t}}
\treturn err
}}
""")
    add("""func (o *Organism) Handle(raw []byte) map[string]any {
\tvar m map[string]any
\tif err := json.Unmarshal(raw, &m); err != nil {
\t\treturn map[string]any{"status": "error", "reason": "bad json"}
\t}
\treturn o.HandleMap(m)
}
""")
    add(f"""func (o *Organism) HandleMap(m map[string]any) map[string]any {{
\to.mu.Lock()
\tdefer o.mu.Unlock()
\tid, _ := m["id"].(string)
\tif id == "" {{
\t\treturn map[string]any{{"status": "error", "reason": "event requires non-empty str 'id'"}}
\t}}
\ttyp, _ := m["type"].(string)
\tknown := false
\tswitch typ {{
{chr(10).join(f'\tcase "{evn}": known = true' for evn in sorted(g.events))}
\t}}
\tif !known {{
\t\treturn map[string]any{{"status": "error", "reason": "unknown event type '" + typ + "'"}}
\t}}
\tif rb, e := json.Marshal(m); e == nil {{ o.appendLog(rb) }}
\tif o.dedup(id) {{
\t\to.counters["dup"]++
\t\treturn map[string]any{{"status": "dup", "id": id}}
\t}}
\toutcomes := map[string]string{{}}
\terr := o.dispatch(typ, m, id, outcomes, 0)
\tif err != nil {{
\t\treturn map[string]any{{"status": "error", "reason": err.Error()}}
\t}}
{inv_checks}
\to.counters["applied"]++
\treturn map[string]any{{"status": "applied", "id": id, "outcomes": outcomes}}
}}

func (o *Organism) replay() int {{
\tpath := filepath.Join(o.dataDir, "events.jsonl")
\tf, err := os.Open(path)
\tif err != nil {{
\t\treturn 0
\t}}
\tdefer f.Close()
\to.replaying = true
\tn := 0
\tsc := bufio.NewScanner(f)
\tfor sc.Scan() {{
\t\tline := sc.Bytes()
\t\tif len(line) > 0 {{
\t\t\to.Handle(append([]byte{{}}, line...))
\t\t\tn++
\t\t}}
\t}}
\to.replaying = false
\treturn n
}}
""")
    # ---- state snapshot for HTTP
    st_cases = "\n".join(
        f'\tcase "{en}":\n\t\tif st, ok := o.{goname(en)}[inst]; ok {{ return st, true }}'
        for en in sorted(g.entities))
    add(f"""func (o *Organism) stateOf(entity, inst string) (any, bool) {{
\tswitch entity {{
{st_cases}
\t}}
\treturn nil, false
}}
""")
    add(_go_dumpall(g))
    add(_go_codec(codec))
    if driver != "http":
        add(_go_door(g, driver, channels))
        return "\n".join(P)
    # ---- HTTP (endpoint parity with the core) + bench mode
    add(f"""func writeJSON(w http.ResponseWriter, code int, v any) {{
\tb, _ := json.Marshal(v)
\tw.Header().Set("Content-Type", "application/json; charset=utf-8")
\tw.WriteHeader(code)
\tw.Write(b)
}}

func main() {{
\tport := "8090"
\tdata := "./data"
\tbench := false
\tfor i := 1; i < len(os.Args); i++ {{
\t\tswitch os.Args[i] {{
\t\tcase "--port":
\t\t\ti++; port = os.Args[i]
\t\tcase "--data":
\t\t\ti++; data = os.Args[i]
\t\tcase "bench":
\t\t\tbench = true
\t\t}}
\t}}
\tif bench {{
\t\trunBench()
\t\treturn
\t}}
\tos.MkdirAll(data, 0o755)
\to := newOrganism(data)
\tn := o.replay()
\to.ledger("replay", map[string]any{{"events": n}})
\tmux := http.NewServeMux()
\tmux.HandleFunc("POST /event", func(w http.ResponseWriter, r *http.Request) {{
\t\tbuf := make([]byte, r.ContentLength)
\t\tr.Body.Read(buf)
\t\tout := o.Handle(buf)
\t\tcode := 200
\t\tif out["status"] == "error" {{
\t\t\tcode = 422
\t\t}}
\t\twriteJSON(w, code, out)
\t}})
\tmux.HandleFunc("POST /skill/{{name}}", func(w http.ResponseWriter, r *http.Request) {{
\t\t// U7 (D71): skills in the go tissue — RPC to the canon (printing bodies is the python tissue).
\t\tcanon := os.Getenv("ONTO_SKILL_CANON")
\t\tif canon == "" {{
\t\t\twriteJSON(w, 501, map[string]any{{"error": "skills are not printed in go-stdlib; set ONTO_SKILL_CANON=<canon base url> for RPC"}})
\t\t\treturn
\t\t}}
\t\tbuf := make([]byte, r.ContentLength)
\t\tio.ReadFull(r.Body, buf)
\t\tresp, err := http.Post(canon+"/skill/"+r.PathValue("name"), "application/json", bytes.NewReader(buf))
\t\tif err != nil {{
\t\t\twriteJSON(w, 502, map[string]any{{"error": "canon unreachable: " + err.Error()}})
\t\t\treturn
\t\t}}
\t\tdefer resp.Body.Close()
\t\tbody, _ := io.ReadAll(resp.Body)
\t\tw.Header().Set("Content-Type", "application/json; charset=utf-8")
\t\tw.WriteHeader(resp.StatusCode)
\t\tw.Write(body)
\t}})
\tmux.HandleFunc("GET /state/{{entity}}/{{inst}}", func(w http.ResponseWriter, r *http.Request) {{
\t\to.mu.Lock()
\t\tdefer o.mu.Unlock()
\t\tif st, ok := o.stateOf(r.PathValue("entity"), r.PathValue("inst")); ok {{
\t\t\twriteJSON(w, 200, st)
\t\t\treturn
\t\t}}
\t\twriteJSON(w, 404, map[string]any{{"error": "no state"}})
\t}})
\tmux.HandleFunc("GET /q/{{name}}", func(w http.ResponseWriter, r *http.Request) {{
\t\to.mu.Lock()
\t\tdefer o.mu.Unlock()
\t\tif v, ok := o.query(r.PathValue("name")); ok {{
\t\t\twriteJSON(w, 200, map[string]any{{"value": v}})
\t\t\treturn
\t\t}}
\t\twriteJSON(w, 404, map[string]any{{"error": "unknown query"}})
\t}})
\tmux.HandleFunc("GET /dump", func(w http.ResponseWriter, r *http.Request) {{
\t\to.mu.Lock(); defer o.mu.Unlock()
\t\tw.Header().Set("Content-Type", "application/json; charset=utf-8")
\t\tw.Write([]byte(o.dumpAll()))
\t}})
\tmux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) {{
\t\to.mu.Lock()
\t\tdefer o.mu.Unlock()
\t\twriteJSON(w, 200, map[string]any{{"ok": true, "counters": o.counters, "genome": "{g.name}"}})
\t}})
\tfmt.Println("organism '{g.name}' (go-stdlib, printed from reference) on :" + port)
\thttp.ListenAndServe("127.0.0.1:"+port, mux)
}}
""")
    add(_bench_go(g))
    return "\n".join(P)


def _bench_go(g: Genome) -> str:
    """bench mode: the full Handle path (no disk: dataDir="") — a comparison
    against the canonical interpreter, exam F2(v)."""
    en = next(iter(g.entities))
    evn = next(iter(g.events))
    ev_fields = {f: ('"' + (g.entities[en].instances[0]
                            if f == g.key_field(en) else "x") + '"')
                 if t == "str" else "float64(1)"
                 for f, t in g.events[evn].items()}
    lits = ", ".join(f'"{f}": {v}' for f, v in sorted(ev_fields.items()))
    from onto.dialects.go_stdlib.rulebench import rule_bench_go
    rule_bench = rule_bench_go(g)
    return f"""func runBench() {{
\to := newOrganism("")
\tconst N = 200000
\traws := make([][]byte, N)
\tfor i := 0; i < N; i++ {{
\t\tm := map[string]any{{"id": fmt.Sprintf("b%d", i), "type": "{evn}", {lits}}}
\t\tb, _ := json.Marshal(m)
\t\traws[i] = b
\t}}
\tstart := time.Now()
\tfor i := 0; i < N; i++ {{
\t\to.Handle(raws[i])
\t}}
\tel := time.Since(start)
\tfmt.Printf("bench full-path: %d events, %.0f ns/op, %.0f events/s\\n",
\t\tN, float64(el.Nanoseconds())/N, float64(N)/el.Seconds())
{rule_bench}}}
"""


def _go_dumpall(g) -> str:
    L = ["func (o *Organism) dumpAll() string {",
         "\tvar b strings.Builder",
         '\tb.WriteString("{")']
    for i, en in enumerate(sorted(g.entities)):
        ent = g.entities[en]
        En = goname(en)
        if i > 0:
            L.append('\tb.WriteString(",")')
        L.append('\tb.WriteString("\\"' + en + '\\":{")')
        L.append("\t{ keys := make([]string,0,len(o.%s)); for k := range o.%s { keys = append(keys,k) }; sort.Strings(keys)" % (En, En))
        ffmt, args = [], []
        for f in sorted(ent.state):
            ffmt.append('\\"' + f + '\\":' + ("%q" if ent.state[f] == "str" else "%d"))
            args.append("st." + goname(f))
        go_fmt = '\\"%s\\":{' + ",".join(ffmt) + '}'
        L.append('\tfor j,k := range keys { if j>0 { b.WriteString(",") }; st := o.%s[k]; b.WriteString(fmt.Sprintf("%s", k, %s)) } }'
                 % (En, go_fmt, ", ".join(args)))
        L.append('\tb.WriteString("}")')
    L.append('\tb.WriteString("}")')
    L.append("\treturn b.String()")
    L.append("}")
    return "\n".join(L)


def _go_door(g, driver: str, channels=None) -> str:
    if driver in ("file", "stdio"):
        if driver == "file":
            read = ('src := ""; if len(os.Args) > 1 { src = os.Args[1] }; var lines []string; '
                    'if src != "" { data, _ := os.ReadFile(src); lines = strings.Split(string(data), "\\n") } '
                    'else { sc := bufio.NewScanner(os.Stdin); sc.Buffer(make([]byte,1024*1024),1024*1024); '
                    'for sc.Scan() { lines = append(lines, sc.Text()) } }')
        else:
            read = ('var lines []string; sc := bufio.NewScanner(os.Stdin); sc.Buffer(make([]byte,1024*1024),1024*1024); '
                    'for sc.Scan() { lines = append(lines, sc.Text()) }')
        return ("func main() {\n\to := newOrganism(\"\")\n\t" + read +
                "\n\tfor _, l := range lines { if strings.TrimSpace(l) == \"\" { continue }; o.HandleWire(l) }"
                "\n" + _go_drain(channels) +
                "\tfmt.Println(o.dumpAll())\n}\n")
    return _GO_TCP_DOOR

_GO_TCP_DOOR = r'''func handleTCP(conn net.Conn, o *Organism) {
	defer conn.Close()
	sc := bufio.NewScanner(conn)
	sc.Buffer(make([]byte,1024*1024),1024*1024)
	for sc.Scan() {
		t := strings.TrimSpace(sc.Text())
		var resp string
		if t == "" { continue } else if t == "?dump" { o.mu.Lock(); resp = o.dumpAll(); o.mu.Unlock()
		} else if strings.HasPrefix(t, "?state/") {
			seg := strings.Split(t[7:], "/")
			if len(seg) == 2 { o.mu.Lock(); if st, ok := o.stateOf(seg[0], seg[1]); ok { bb,_ := json.Marshal(st); resp = string(bb) } else { resp = "null" }; o.mu.Unlock() } else { resp = "null" }
		} else { o.HandleWire(t); resp = "{\"status\":\"applied\"}" }
		if resp != "" { conn.Write([]byte(resp + "\n")) }
	}
}

func main() {
	bind := "127.0.0.1:8610"
	for i := 1; i < len(os.Args); i++ {
		if os.Args[i] == "--port" && i+1 < len(os.Args) { i++; bind = "127.0.0.1:" + os.Args[i] }
		if os.Args[i] == "--bind" && i+1 < len(os.Args) { i++; bind = os.Args[i] }
	}
	o := newOrganism("")
	ln, err := net.Listen("tcp", bind); if err != nil { panic(err) }
	fmt.Fprintln(os.Stderr, "go-stdlib organism (TCP door) on "+bind)
	for { conn, err := ln.Accept(); if err != nil { continue }; handleTCP(conn, o) }
}
'''



def _go_codec(codec: str) -> str:
    if codec == "kv":
        pw = ('func parseWire(line string) map[string]any {\n'
              '\tm := map[string]any{}\n'
              '\tfor _, part := range strings.Split(strings.TrimSpace(line), ";") {\n'
              '\t\tp := strings.TrimSpace(part); if p == "" { continue }\n'
              '\t\ti := strings.Index(p, "="); if i < 0 { continue }\n'
              '\t\tk := strings.TrimSpace(p[:i]); v := strings.TrimSpace(p[i+1:])\n'
              '\t\tif n, err := strconv.ParseFloat(v, 64); err == nil { m[k] = n } else { m[k] = v }\n'
              '\t}\n\treturn m\n}\n')
    else:
        pw = ('func parseWire(line string) map[string]any {\n'
              '\tvar m map[string]any\n\tjson.Unmarshal([]byte(line), &m)\n\treturn m\n}\n')
    return pw + 'func (o *Organism) HandleWire(line string) map[string]any { return o.HandleMap(parseWire(line)) }\n'


def _go_drain(channels) -> str:
    outs = [c for c in (channels or []) if c.get("direction") == "out"]
    out = ""
    for oc in outs:
        if oc.get("driver", "file") != "file":
            continue
        sink = oc.get("path", "out.jsonl")
        on = oc.get("on", [])
        cond = (" || ".join(f'strings.Contains(ev, "\\"type\\":\\"{e}\\"")' for e in on)
                if on else "true")
        out += ('\t{ if _f, _e := os.OpenFile("%s", os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644); _e == nil {\n'
                '\t\tfor _, ev := range o.outEvents { if %s { _f.WriteString(ev + "\\n") } }\n'
                '\t\t_f.Close() } }\n') % (sink, cond)
    return out

